services:
  portal:
    build:
      context: ..
      dockerfile: portal/Dockerfile
    container_name: caisbe-portal
    restart: unless-stopped
    ports:
      - "3002:3000"
    environment:
      API_URL: http://caisbe-api:8000
      NEXT_PUBLIC_SITE_URL: http://localhost:3000
      NEXT_PUBLIC_ADMIN_URL: http://localhost:3001
      NEXT_PUBLIC_PORTAL_URL: http://localhost:3002
    networks:
      - default
      - caisbe_dev
    develop:
      watch:
        - action: sync
          path: .
          target: /app/portal
          ignore:
            - node_modules/
            - .next/
        - action: rebuild
          path: ./package.json

networks:
  caisbe_dev:
    external: true
    name: caisbe_dev
