"""IANA timezone and ISO country codes used when a CDN country header is absent."""

TIMEZONE_COUNTRIES: dict[str, str] = {
    "Africa/Abidjan": "Côte d'Ivoire",
    "Africa/Accra": "Ghana",
    "Africa/Addis_Ababa": "Ethiopia",
    "Africa/Algiers": "Algeria",
    "Africa/Cairo": "Egypt",
    "Africa/Casablanca": "Morocco",
    "Africa/Dar_es_Salaam": "Tanzania",
    "Africa/Johannesburg": "South Africa",
    "Africa/Kampala": "Uganda",
    "Africa/Khartoum": "Sudan",
    "Africa/Kigali": "Rwanda",
    "Africa/Lagos": "Nigeria",
    "Africa/Maputo": "Mozambique",
    "Africa/Nairobi": "Kenya",
    "Africa/Tunis": "Tunisia",
    "America/Chicago": "United States",
    "America/Denver": "United States",
    "America/Los_Angeles": "United States",
    "America/Mexico_City": "Mexico",
    "America/New_York": "United States",
    "America/Sao_Paulo": "Brazil",
    "America/Toronto": "Canada",
    "America/Vancouver": "Canada",
    "America/Winnipeg": "Canada",
    "Asia/Dubai": "United Arab Emirates",
    "Asia/Hong_Kong": "Hong Kong",
    "Asia/Kolkata": "India",
    "Asia/Shanghai": "China",
    "Asia/Singapore": "Singapore",
    "Asia/Tokyo": "Japan",
    "Australia/Sydney": "Australia",
    "Europe/Amsterdam": "Netherlands",
    "Europe/Berlin": "Germany",
    "Europe/Brussels": "Belgium",
    "Europe/London": "United Kingdom",
    "Europe/Madrid": "Spain",
    "Europe/Paris": "France",
    "Europe/Rome": "Italy",
    "Europe/Stockholm": "Sweden",
    "UTC": "Unknown",
}

ISO_COUNTRIES: dict[str, str] = {
    "AU": "Australia",
    "BE": "Belgium",
    "BR": "Brazil",
    "CA": "Canada",
    "CN": "China",
    "DE": "Germany",
    "EG": "Egypt",
    "ES": "Spain",
    "ET": "Ethiopia",
    "FR": "France",
    "GB": "United Kingdom",
    "GH": "Ghana",
    "IN": "India",
    "IT": "Italy",
    "JP": "Japan",
    "KE": "Kenya",
    "MA": "Morocco",
    "NG": "Nigeria",
    "NL": "Netherlands",
    "RW": "Rwanda",
    "SE": "Sweden",
    "SG": "Singapore",
    "TZ": "Tanzania",
    "UG": "Uganda",
    "US": "United States",
    "ZA": "South Africa",
}
